#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
import argparse
import sys

FIRST = 0x20
LAST = 0x7e


def fail(msg):
    sys.exit(f"bdf2c: {msg}")


def parse(path):
    cell = None
    glyphs = {}
    copyright_line = None
    encoding = bbx = rows = None
    with open(path, encoding="ascii") as f:
        for raw in f:
            words = raw.split()
            if not words:
                continue
            key = words[0]
            if rows is not None:
                if key == "ENDCHAR":
                    if encoding is not None and FIRST <= encoding <= LAST:
                        glyphs[encoding] = (bbx, rows)
                    encoding = bbx = rows = None
                else:
                    rows.append(int(words[0], 16))
            elif key == "FONTBOUNDINGBOX":
                cell = tuple(int(w) for w in words[1:5])
            elif key == "COPYRIGHT":
                copyright_line = raw.split(None, 1)[1].strip().strip('"')
            elif key == "ENCODING":
                encoding = int(words[1])
            elif key == "BBX":
                bbx = tuple(int(w) for w in words[1:5])
            elif key == "BITMAP":
                rows = []
    if cell is None:
        fail(f"{path}: no FONTBOUNDINGBOX")
    return cell, glyphs, copyright_line


def place(cell, code, bbx, rows):
    cell_w, cell_h, cell_x, cell_y = cell
    w, h, x, y = bbx
    left = x - cell_x
    top = (cell_h + cell_y) - (h + y)
    if left < 0 or top < 0 or left + w > cell_w or top + h > cell_h or len(rows) != h:
        fail(f"glyph 0x{code:02x} does not fit the {cell_w}x{cell_h} cell")
    row_bits = (w + 7) // 8 * 8
    out = [0] * cell_h
    for i, bits in enumerate(rows):
        for col in range(w):
            if bits >> (row_bits - 1 - col) & 1:
                out[top + i] |= 1 << (cell_w - 1 - (left + col))
    return out


def render(path, cell, glyphs, copyright_line):
    cell_w, cell_h = cell[0], cell[1]
    if cell_w > 32:
        fail(f"cell width {cell_w} does not fit a uint32_t row")
    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        fail(f"missing glyphs: {', '.join(f'0x{c:02x}' for c in missing)}")
    lines = [
        "/* SPDX-License-Identifier: BSD-2-Clause */",
        f"/* generated by tools/bdf2c.py from {path.rsplit('/', 1)[-1]}: {copyright_line} */",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define FONT_W {cell_w}u",
        f"#define FONT_H {cell_h}u",
        f"#define FONT_FIRST 0x{FIRST:02x}u",
        f"#define FONT_LAST 0x{LAST:02x}u",
        "",
        f"static const uint32_t font_rows[{LAST - FIRST + 1}][{cell_h}] = {{",
    ]
    for code in range(FIRST, LAST + 1):
        bbx, rows = glyphs[code]
        placed = place(cell, code, bbx, rows)
        lines.append("    {" + ", ".join(f"0x{r:x}" for r in placed) + "},")
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Turn a BDF bitmap font into a C glyph table for fbcon.")
    parser.add_argument("bdf")
    parser.add_argument("out")
    args = parser.parse_args()

    cell, glyphs, copyright_line = parse(args.bdf)
    if copyright_line is None:
        fail(f"{args.bdf}: no COPYRIGHT property")
    text = render(args.bdf, cell, glyphs, copyright_line)
    with open(args.out, "w", encoding="ascii") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
