#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-2-Clause
set -euo pipefail

if [ $# -ne 4 ]; then
    echo "usage: $0 <device.txt> <device.dtb> <flake.lock> <out.h>" >&2
    exit 2
fi

txt=$1
dtb=$2
lock=$3
out=$4

die() {
    echo "gen-trace-stamp: $*" >&2
    exit 1
}

field() {
    sed -n "s/^$1[[:space:]]\{1,\}//p" "$txt" | head -n 1
}

check_len() {
    local name=$1 value=$2 max=$3
    [ -n "$value" ] || die "$name is empty in $txt"
    [ "${#value}" -lt "$max" ] || die "$name '$value' does not fit $max bytes"
}

codename=$(field fingerprint | cut -d/ -f2)
build_id=$(field build_id)
bootloader=$(field bootloader)
baseband=$(field baseband)
dtb_sha256=$(sha256sum "$dtb" | cut -d' ' -f1)
toolchain_sha256=$(sha256sum "$lock" | cut -d' ' -f1)
repo=$(git -C "$(dirname "$0")" rev-parse --show-toplevel)
git_sha=$(git -C "$repo" rev-parse HEAD)
if [ -n "$(git -C "$repo" status --porcelain)" ]; then
    git_sha="$git_sha-dirty"
fi

[ "$dtb_sha256" = "$(field sha256)" ] || die "$dtb sha256 does not match $txt"

check_len codename "$codename" 16
check_len build_id "$build_id" 32
check_len bootloader "$bootloader" 48
check_len baseband "$baseband" 48
check_len git_sha "$git_sha" 48

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
cat > "$tmp" <<EOF
/* Generated by tools/gen-trace-stamp.sh. */
#pragma once
#define TRACE_STAMP_CODENAME "$codename"
#define TRACE_STAMP_BUILD_ID "$build_id"
#define TRACE_STAMP_BOOTLOADER "$bootloader"
#define TRACE_STAMP_BASEBAND "$baseband"
#define TRACE_STAMP_GIT_SHA "$git_sha"
#define TRACE_STAMP_TOOLCHAIN_SHA256 "$toolchain_sha256"
#define TRACE_STAMP_DTB_SHA256 "$dtb_sha256"
EOF

if ! cmp -s "$tmp" "$out" 2>/dev/null; then
    mkdir -p "$(dirname "$out")"
    mv "$tmp" "$out"
fi
